config/routes.rb
Rails.application.routes.draw do
 resources :vehicles do
  resources :bookings, only: [:create]
 end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/rentals', to: 'bookings#rentals'
  resources :bookings, only: [:index, :destroy]
end

# Pseudo coding
# get "pages/show", to: "pages#show"
# patch "pages/show/:id", to: "pages#update"

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  
  validates :date, presence: true, allow_blank: false
  validates :end_date, presence: true, allow_blank: false
  validate :end_date_after_start_date

  def end_date_after_start_date
    if end_date.present?
      errors.add(:end_date, "can't be before your start date!") if end_date <= date
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :skip_authorization, only: [:rentals, :destroy]

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    vehicle = Vehicle.find(params[:vehicle_id])
    @booking.vehicle = vehicle
    @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        redirect_to vehicle_path(vehicle)
      end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  def index
    @bookings = policy_scope(current_user.bookings)
  end

  def rentals
    @rentals = current_user.vehicles.map do |vehicle|
    vehicle.bookings
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :end_date)
  end
end

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<div class="container mt-3"  id="space-full-screen">
  <h1>My bookings</h1>

  <% @bookings.each do |booking| %>
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <%= link_to vehicle_path(booking.vehicle) do %>
              <%= cl_image_tag booking.vehicle.image_url.key, class:"img-fluid rounded-start" %>
            <% end %>
          </div>
          <div class="col-md-8 m-0">
            <div class="card-body lh-1">
              <h5 class="card-title"><%= booking.vehicle.category %> in <%= booking.vehicle.location %></h5>
              <p class="card-text">Owner: <%= booking.vehicle.user.full_name %></p>
              <p class="card-text mb-0">Price: $ <%= booking.vehicle.price %>/day</p>
              <p class="card-text mb-0"><small class="text-muted">Pick up: <%= booking.date %></small></p>
              <div class="d-flex justify-content-between">
              <p class="card-text mb-0"><small class="text-muted">Return: <%= booking.end_date %></small></p>           
                <%= link_to "Delete booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-je ml-5 justify-content-end" %>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/bookings/rentals.html.erb
<div class="container mt-3"  id="space-full-screen">
  <h1>Your Rentals</h1>

<% @rentals.each do |rentals| %>
  <% rentals.each do |rental| %>
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <%= link_to vehicle_path(rental.vehicle) do %>
            <%= cl_image_tag rental.vehicle.image_url.key, class:"img-fluid rounded-start" %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= rental.vehicle.category %> in <%= rental.vehicle.location %></h5>
            <p class="card-text">Renter: <%= rental.user.full_name %></p>
            <p class="card-text mb-0">Price: $ <%= rental.vehicle.price %>/day</p>
            <p class="card-text mb-0"><small class="text-muted">Pick up: <%= rental.date %></small></p>
            <div class="d-flex justify-content-between">
            <p class="card-text mb-0"><small class="text-muted">Return: <%= rental.end_date %></small></p>    
              <%= link_to "Delete this rental", booking_path(rental), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-je ml-5" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>