config/routes.rb
Rails.application.routes.draw do
 resources :vehicles do
  resources :bookings, only: [:create]
 end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/rentals', to: 'bookings#rentals'
  resources :bookings, only: [:index, :destroy]
end

# Pseudo coding
# get "pages/show", to: "pages#show"
# patch "pages/show/:id", to: "pages#update"

app/views/shared/_footer.html.erb
<div class="footer"> 
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Produced by MoNo CoN NaVaJa <i class="em em-monkey" aria-role="presentation" aria-label="MONKEY"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://mobike.com/global/public/download__app_icon.png" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <h1 class="display-8">youRide</h1>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= link_to "Post a vehicle!", new_vehicle_path, class:"btn btn-ghost mr-3" %>
        
        <% if user_signed_in? %>
          <% photo = current_user.profile_picture %>
          <li class="nav-item dropdown">
            <%= image_tag photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Your rentals", rentals_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My account", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
          </li>
        <% end %>
        
      </ul>
    </div>
</div>