config/routes.rb
Rails.application.routes.draw do
 resources :vehicles do
  resources :bookings, only: [:create]
 end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/rentals', to: 'bookings#rentals'
  resources :bookings, only: [:index, :destroy]
end

# Pseudo coding
# get "pages/show", to: "pages#show"
# patch "pages/show/:id", to: "pages#update"

app/views/pages/account.html.erb
<%= simple_form_for @info do |f| %>
 <%= f.input :email %>
<% end %>

app/views/pages/home.html.erb
<div class="banner pt-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/ddwduhayz/image/upload/v1625179936/photo-1612270237088-d1262c013709_qzfd4x.jpg);">
  <div class="container d-flex flex-column mb-5">
    <h1 class="mb-4"><strong>Choose your next ride</strong>!</h1>
    <h4 class="mb-4" style="color:rgb(246, 129, 114); font-family:Nunito";>Quick and easy online mobility rental platform!</h4>
    <div>
      <%= form_tag vehicles_path, method: :get, class:"d-flex justify-content-between w-75" do %>
        <%= text_field_tag :query, params[:query], class: "form-control ", id:"vehicle_location", placeholder: "Location", style:"border-radius: 2px; width: 400px;"%>
        <%= number_field_tag :price, params[:price], min: 0, class: "form-control", placeholder: "Price", style:"border-radius: 2px; width: 300px;"%>
        <%= select_tag "category", raw("<option>Bicycle</option><option>E-bike</option><option>Scooter</option><option>Wheel Chair</option><option>Skate</option><option>Rollers</option>"), class: "form-control", style:"border-radius: 2px; width: 410px;"%>
        <%= submit_tag "Search", class: "btn btn-ghost", style:"border-radius: 2px; padding: 0 15px;" %>
      <% end %>
      </div>
    </div>
  </div>
</div>


  <h2 class="text-center mt-3">Our categories</h2>

  <div class="container mt-3 d-flex">
    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1592568260540-58c62d2b2f7c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8ZSUyMGJpa2V8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60')">
        <p>E-Bike</p>
      </div>
    <% end %>

    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1605021132832-3d59e5ce90f4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fHNjb290ZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60')">
        <p>Scooter</p>
      </div>
    <% end %>

    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1570679334008-c97544c8695b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDB8fGJpY3ljbGV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60')">
        <p>Bicycle</p>
      </div>
    <% end %>
  </div>

  <div class="container mt-1 d-flex">
    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1595687973201-0095ff7a302e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8d2hlZWwlMjBjaGFpcnxlbnwwfDB8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60')">
        <p>Wheel Chair</p>
      </div>
    <% end %>

    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1476344988293-1d5501af75a6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8c2thdGV8ZW58MHwwfDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60')">
        <p>Skate</p>
      </div>
    <% end %>

    <%= link_to "/vehicles" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1583832292569-7092d6d90873?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cm9sbGVyfGVufDB8MHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60')">
        <p>Rollers</p>
      </div>
    <% end %>
  </div>