config/routes.rb
Rails.application.routes.draw do
 resources :vehicles do
  resources :bookings, only: [:create]
 end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/rentals', to: 'bookings#rentals'
  resources :bookings, only: [:index, :destroy]
end

# Pseudo coding
# get "pages/show", to: "pages#show"
# patch "pages/show/:id", to: "pages#update"

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  
  validates :location, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :title, presence: true, length: {minimum: 8}
  validates :description, presence: true, length: {minimum: 8}
  validates :category, presence: true

  has_one_attached :image_url
  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: :new

def index
  @vehicles = policy_scope(Vehicle)
  if params[:query].present?
    @vehicles = Vehicle.near(params[:query], 10)
    if @vehicles == []
      @vehicles = Vehicle.all 
    else 
      @vehicles = Vehicle.where(category: params[:category], id: @vehicles.collect(&:id))
      @vehicles = @vehicles.where(price: (0..params[:price].to_i)) if params[:price].present?
    end
  end
  @markers = @vehicles.geocoded.map do |vehicle|
    {
      lat: vehicle.latitude,
      lng: vehicle.longitude,
      info_window: render_to_string(partial: "info_window", locals: { vehicle: vehicle })
    }
    end
end

  def show
    @booking = Booking.new
    authorize @vehicle
    @marker = [{lat:@vehicle.geocode[0], lng:@vehicle.geocode[1] }]
  end

  def new
    @vehicle = Vehicle.new
    authorize @vehicle
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    authorize @vehicle
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def update
    authorize @vehicle
    if @vehicle.update(vehicle_params)
      redirect_to vehicle_path(@vehicle)
    else
      render :edit
    end
  end

  def destroy
    authorize @vehicle
    @vehicle.destroy
    redirect_to vehicles_path
  end

  def edit
    authorize @vehicle
  end

  private

  def find
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:category, :price, :title, :location, :description, :image_url)
  end

end

app/views/vehicles/_info_window.html.erb
<div class="container text-center">
 <h4><%= vehicle.category %></h4>
 <p>$ <%= vehicle.price %>/day</p>
 <%= link_to 'See details', vehicle_path(vehicle), class:"btn btn-ghost px-2 py-1", style:"font-size: 11px;"%>
</div>

app/views/vehicles/create.html.erb
<h1>Vehicles#create</h1>
<p>Find me in app/views/vehicles/create.html.erb</p>

app/views/vehicles/detroy.html.erb
<h1>Vehicles#detroy</h1>
<p>Find me in app/views/vehicles/detroy.html.erb</p>

app/views/vehicles/edit.html.erb
<div class="container mt-3" id="space-full-screen">
 <h1>Edit your vehicle: <%= @vehicle.category %></h1>
 <%= simple_form_for @vehicle do |f| %>
  <%= f.input :category, :collection => ["Bicycle", "E-bike", "Scooter", "Wheel Chair", "Skate", "Rollers"], label: "Edit your vehicle category" %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :price %>
  <%= f.input :image_url, as: :file %>
  <%= f.input :description %>
  <%= f.submit %>
 <% end %>
</div>

app/views/vehicles/index.html.erb
<div class="container mt-3">
  <h1>All our vehicles</h1>
  <div class="row">
    <div class="col-5 pl-0">
    <% @vehicles.each do |vehicle| %>
      <%= link_to vehicle_path(vehicle) do %>
        <div class="card-trip">
          <%= cl_image_tag vehicle.image_url.key %>
          <div class="card-trip-infos">
            <div>
              <h2><%= vehicle.category %></h2>
              <p style="width: 165px;"><%= vehicle.title %></p>
            </div>
            <p class="card-trip-pricing" style="width: 63px;  font-size: 15px;">$ <%= vehicle.price %>/day</p>
            <img src=<%= vehicle.user.profile_picture %> class="card-trip-user avatar-bordered" style="width: 50px;" />
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
    <div id="map" class="map-index col-7 mt-3"
      style="width: 600vw; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container mt-3" id="space-full-screen">
  <h1>Create a new vehicle!</h1>
  <%= simple_form_for @vehicle do |f| %>
    <%= f.input :category, :collection => ["Bicycle", "E-bike", "Scooter", "Wheel Chair", "Skate", "Rollers"] %>
    <%= f.input :title %>
    <%= f.input :location %>
    <%= f.input :price %>
    <%= f.input :image_url, as: :file %>
    <%= f.input :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/vehicles/show.html.erb
<div class="banner pt-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @vehicle.image_url.key, crop: :fill %>');">
  <div class="container d-flex flex-column mb-5">
    <% unless policy(@vehicle).destroy? %>
      <%= link_to "All vehicles", vehicles_path, class:"btn btn-light mb-4", style:"width: 150px;" %>
    <% else %>
      <%= link_to "Your rents", vehicles_path, class:"btn btn-light mb-4", style:"width: 150px;" %>
    <% end %>
    <h1 class="mb-5"><strong><%=  @vehicle.category %></strong>!</h1>
    <div>
      <h3 class="mb-1"><strong><%= @vehicle.title %></strong></h3>
      <div class="d-flex align-items-center">
      <img src=<%= @vehicle.user.profile_picture %> class="mb-4 mr-2" style="border-radius: 50%; width: 50px;"/>
      <h4 class="my-5"><%=  @vehicle.user.full_name %></h4>
      </div>
    </div>
  </div>
  <div>
</div>

<div class="container mt-4">
  <div class="d-flex justify-content-around mr-3">
    <div>
      <div id="map" class="show-map mr-1 "
        style="width: 550px; height: 600px;"
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
    <div style="width: 350px; " class="text-center d-flex justify-content-center align-items-center">
      <div class=" shadow" style="width: 100%; padding: 60px 50px; border-radius: 15px" >
        <h5 class="mb-3" style="font-size: 25px;">Price: $<%= @vehicle.price %>/day</h5>
        <p class="mb-5" style="font-size: 25px;"><%= @vehicle.description %></p>
        <% unless policy(@vehicle).destroy? %>
          <%= simple_form_for [@vehicle, @booking] do |f| %>
            <%= f.error_notification %>
              <%= f.input :date, as: :string, required: true, input_html: {class: "datepicker"} %>
              <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"} %>
              <%= f.submit "Book", class:"btn btn-ghost btn-block mt-3" %>
            <% end %>
          <% end %> 
        <% if policy(@vehicle).destroy? %>
          <%= link_to 'Edit this vehicle', edit_vehicle_path, class:"btn btn-je je w-100", id:"je" %>
        <% end %>
        <% if policy(@vehicle).destroy? %>
          <%= link_to "Delete this vehicle", vehicle_path(@vehicle), method: :delete, class:"btn btn-je mt-4 w-100", style:"font-size: 18px;", data: { confirm: "Are you sure to destroy this vehicle?"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>